version: "3.3"
services:
  mysql:
      image: mysql
      container_name: mysql
      ports:
          - 3306:3306
      environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cv19
      networks: 
        - share-network
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
      container_name: elasticsearch
      environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      cap_add:
        - IPC_LOCK
      ports:
        - 9200:9200
        - 9300:9300  
      networks:
        - share-network          

  logstash:
      image: docker.elastic.co/logstash/logstash:7.6.2
      container_name: logstash
      depends_on:
         - elasticsearch
         - mysql
      ports:
          - 5044:5044
      volumes:
          - ./:/mnt/c/users/j9872/desktop/projects/cv19-data
      command: logstash -f /mnt/c/users/j9872/desktop/projects/cv19-data/logstash.conf    
      environment:
          - ELASTIC_INDEX=transactions
          - ELASTIC_DOC_TYPE=transactions
          - ELASTIC_HOSTS=elasticsearch
          - MYSQL_HOST=mysql
          - MYSQL_ROOT_USER=root
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DB_NAME=cv19
      networks:
        - share-network
networks:
  share-network: